<!-- Include local javascript from js/... -->
<!--suppress HtmlUnknownTarget -->
<script type="text/javascript" src="js/app.js"></script>
<!--suppress HtmlUnknownTarget -->
<script type="text/javascript" src="js/controllers.js"></script>
<!--suppress HtmlUnknownTarget -->
<script type="text/javascript" src="js/routes.js"></script>
<!--suppress HtmlUnknownTarget -->
<script type="text/javascript" src="js/services.js"></script>
<!--suppress HtmlUnknownTarget -->
<script type="text/javascript" src="js/mods.js"></script>
<!--suppress HtmlUnknownTarget -->
<script type="text/javascript" src="js/constants.js"></script>
<!-- Controllers -->
<!--suppress HtmlUnknownTarget -->
<script type="text/javascript" src="js/new-container-ctrl.js"></script>
<!--suppress HtmlUnknownTarget -->
<script type="text/javascript" src="js/view-containers-ctrl.js"></script>
<!--suppress HtmlUnknownTarget -->
<script type="text/javascript" src="js/upload-mod-ctrl.js"></script>
<!--suppress HtmlUnknownTarget -->
<script type="text/javascript" src="js/manage-mods-ctrl.js"></script>
